# insert_shape

In [1]:
import numpy as np
import porespy as ps
import matplotlib.pyplot as plt
ps.visualization.set_mpl_style()
np.random.seed(10)

insert_shape uses the inputs of im, element, center=None, corner=None, value=1, mode="overwrite" to insert the element into the image. The center and corner variables determine where the element is inserted witin the image, and the value determines how the element is scaled. Mode is to specify if the element added overwirtes the image, or if it is overlayed ith the image.

In [2]:
image = np.random.randint(10, size=(5,5,5))
element =np.random.randint(10, size=(3,3,3))
print(image)
print(element)

[[[9 4 0 1 9]
  [0 1 8 9 0]
  [8 6 4 3 0]
  [4 6 8 1 8]
  [4 1 3 6 5]]

 [[3 9 6 9 1]
  [9 4 2 6 7]
  [8 8 9 2 0]
  [6 7 8 1 7]
  [1 4 0 8 5]]

 [[4 7 8 8 2]
  [6 2 8 8 6]
  [6 5 6 0 0]
  [6 9 1 8 9]
  [1 2 8 9 9]]

 [[5 0 2 7 3]
  [0 4 2 0 3]
  [3 1 2 5 9]
  [0 1 0 1 9]
  [0 9 2 1 1]]

 [[0 0 5 9 0]
  [4 6 6 0 2]
  [3 3 2 6 0]
  [5 1 3 6 5]
  [5 1 8 0 5]]]
[[[9 8 5]
  [7 8 5]
  [8 9 9]]

 [[1 5 9]
  [1 4 7]
  [7 7 9]]

 [[7 6 0]
  [3 9 4]
  [4 6 8]]]


The image array and shape array are both arrays of the same dimensions, in this case 3-dimensional arrays.

In [3]:
x = ps.generators.insert_shape(image, element, center=None, corner=[0,0,0], value=1, mode="overwrite")


The element has been added to the image. Since the mode was "overwrite" and the corner was [0,0,0], the image was overwritten with the element anchored in the [0,0,0] corner.