# insert_shape

In [1]:
import porespy as ps
from IPython.display import Markdown as show
show(ps.tools.show_docstring(ps.generators.insert_shape))

---
 ## Documentation for ``insert_shape``
 ---
**<span style="color:purple">insert&#95;shape</span>_(im, element, center=None, corner=None, value=1, mode='overwrite')_**


Inserts sub-image into a larger image at the specified location.


If the inserted image extends beyond the boundaries of the image it will
be cropped accordingly.

#### Parameters
* im : <b><i>ND-array</i></b>  The image into which the sub-image will be inserted
* element : <b><i>ND-array</i></b>  The sub-image to insert
* center : <b><i>tuple</i></b>  Coordinates indicating the position in the main image where the
	inserted imaged will be centered.  If ``center`` is given then
	``corner`` cannot be specified.  Note that ``center`` can only be
	used if all dimensions of ``element`` are odd, otherwise the meaning
	of center is not defined.
* corner : <b><i>tuple</i></b>  Coordinates indicating the position in the main image where the
	lower corner (i.e. [0, 0, 0]) of the inserted image should be anchored.
	If ``corner`` is given then ``corner`` cannot be specified.
* value : <b><i>scalar</i></b>  A scalar value to apply to the sub-image.  The default is 1.
* mode : <b><i>string</i></b>  If 'overwrite' (default) the inserted image replaces the values in the
	main image.  If 'overlay' the inserted image is added to the main
	image.  In both cases the inserted image is multiplied by ``value``
	first.

#### Returns
* im : <b><i>ND-array</i></b>  A copy of ``im`` with the supplied element inserted.
---

## Import packages

In [2]:
import numpy as np
import porespy as ps
import matplotlib.pyplot as plt
ps.visualization.set_mpl_style()
np.random.seed(10)

## Create image and element:

In [3]:
image = np.random.randint(1,3, size=(5,5,5))
element =np.random.randint(10,11, size=(3,3,3))
print(image)
print(element)

[[[2 2 1 2 1]
  [2 2 1 2 2]
  [1 2 2 1 1]
  [2 1 1 1 1]
  [1 2 1 1 2]]

 [[2 1 1 2 1]
  [1 2 1 1 1]
  [2 2 1 2 2]
  [2 2 2 1 2]
  [1 1 1 1 2]]

 [[1 2 2 2 1]
  [2 1 2 2 1]
  [2 1 1 2 1]
  [1 1 2 2 1]
  [1 1 2 1 2]]

 [[2 1 2 2 1]
  [2 1 1 1 1]
  [1 2 1 2 1]
  [1 1 1 1 1]
  [1 2 2 1 2]]

 [[2 1 1 2 1]
  [1 2 1 1 1]
  [1 1 1 2 2]
  [2 1 1 1 2]
  [2 2 2 1 2]]]
[[[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]]


The image array and shape array are both arrays of the same dimensions, in this case 3-dimensional arrays.

## Apply generator function:
With different parameters

### Corner

In [4]:
x = ps.generators.insert_shape(image = image, element=element, center=None, corner=[0,0,0], value=1, mode="overwrite")
print (x)

TypeError: insert_shape() got an unexpected keyword argument 'image'

The element is anchored in the [0, 0, 0] corner.

### Center

In [ ]:
x = ps.generators.insert_shape(image=image, element=element, center=[2,3,2], corner=None, value=1, mode="overwrite")
print (x)

The image is centered at [2, 3, 2].

### Value

In [ ]:
x = ps.generators.insert_shape(image=image, element=element, center=[2,2,2], corner=None, value=5, mode="overwrite")
print (x)

The element was multiplied by value (5), before being inserted to the image.

### Mode

In [ ]:
x = ps.generators.insert_shape(image=image, element=element, center=[2,2,2], corner=None, value=1, mode="overwrite")
print (x)

The element has been inserted to the image. Since the mode was "overwrite" the specified section of the image is replaced by the element.

In [ ]:
x = ps.generators.insert_shape(image=image, element=element, center=[2,2,2], corner=None, value=1, mode="overlay")
print (x)

The element has been inserted to the image. Since the mode was "overlay" the values of the element were added to the values of the image.